version: '3'

services:
  backend:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=backend.app.main
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///data/app.db
      - SECRET_KEY=change_this_in_production
    restart: unless-stopped

  # Uncomment if you want to include Ollama for local AI processing
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ./ollama-data:/root/.ollama
  #   restart: unless-stopped 