repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: check-ast
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: ['--max-line-length=100', '--ignore=D100,D104,E203,W503']

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ['--profile', 'black', '--line-length=100']

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: ['--line-length=100']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]
        args: ['--ignore-missing-imports']

-   repo: https://github.com/python-bandit/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ['-s', 'B101,B104,B603,B311', '-ll'] 